site_name: DGamboa Notes & Snippets
site_url: https://difegam.github.io/dgamboa/
site_author: Diego Gamboa
site_description: A collection of notes and snippets for personal use and sharing with the community.

repo_url: https://github.com/difegam/notes
repo_name: difegam/notes
edit_uri: edit/main/docs/

copyright: |
  &copy; 2024 <a href="https://github.com/difegam"  target="_blank" rel="noopener">Diego Gamboa</a>
theme:
  name: material
  logo: assets/logo.svg
  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  language: en
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - social:
  - blog
  - tags:
      tags_file: tags.md
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      enable_creation_date: true
      enable_last_modified: true
      type: date

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/difegam
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/diegofernandogamboagomez/?locale=en_US
      name: LinkedIn
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/15230097/difegam3
      name: StackOverflow

markdown_extensions:

  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - abbr
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: difegam
      repo: notes

nav:
  - Home: index.md
  - Topics:
    - topics/index.md
    - Git:
      - topics/git/index.md
      - Commands:
        - Basic: topics/git/commands/basic.md
        - Advanced:
          - Rebase: topics/git/commands/rebase.md
      - Guides:
        - Remove leaked env: docs/topics/git/remove_leaked_env.md
    - Python:
      - topics/python/index.md
      - Libraries:
        - Build-in:
          - Collections: topics/python/libraries/pydantic.md
        - External:
          - Pydantic: topics/python/libraries/pydantic.md
          - Arrow: topics/python/libraries/arrow.md
      - Tools:
        - VSCode: topics/python/tools/vscode.md
        - Ruff: topics/python/tools/ruff.md
    - Linux:
      - topics/linux/index.md
      - commands:
        - Basic: topics/linux/commands/basic.md
        - Advanced: topics/linux/commands/advanced.md
    - Docker Containerization:
      - topics/docker/index.md
      - Docker: topics/placeholder.md # Change Me
      - Docker Compose: topics/placeholder.md # Change Me
    - Self-hosting:
      - topics/self-hosting/index.md
      - Services:
        - Traefik: topics/placeholder.md # Change Me
      - Resources:
        - Cloudflare tunnel: topics/placeholder.md # Change Me
    - 3D Printing:
      - topics/3d-printing/index.md
      - 3D Models: topics/placeholder.md # Change Me
      - Ender 3: topics/placeholder.md # Change Me
    - Home Automation:
      - topics/home-automation/index.md
      - Home Assistant: topics/placeholder.md # Change Me
      - ESPHome: topics/placeholder.md # Change Me

  - Articles:
    - blog/index.md
  - Tags: tags.md
  - About:
    - About Me: about/me.md
    - About this site: about/this-site.md
